### ISSUE TITLE
Flowview Clog Error

### ISSUE THREAD

**Issue by wizkid19** [Cacti/plugin_flowview#16]
I added this plugin a while ago and works perfectly, but I notice in my logs that there's a lot of ERROR received. If there's anyone who can help me with the error below. Thank you.

My Flowview version is 2.1 running on latest Cacti version 1.1.27.
My Flow-tools version is 0.68.5.1-15.el7

My current function functions.php is the one I downloaded here <code>.

2017/11/15 15:47:05 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/flowview/flowview.php: 59 flowview_display_report)(/plugins/flowview/functions.php: 100 createfilter)(/plugins/flowview/functions.php: 578 parsestatoutput)(/plugins/flowview/functions.php: 816 flowview_get_dns_from_ip)(/plugins/flowview/functions.php: 1619 unpack)(CactiErrorHandler)(/lib/functions.php: 4403 cacti_debug_backtrace)
--
2017/11/15 15:47:05 - ERROR PHP WARNING in  Plugin 'flowview': unpack(): Type s: not enough input, need 2, have 0 in file: /var/www/html/cacti-1.1.27/plugins/flowview/functions.php  on line: 1619

**Comment by netniV** [comment]
An issue with unpack usually means that the string is invalid.  i'd have to see what is occurring around line 1619 in functions.php

**Comment by netniV** [comment]
Ok, so I decided to take a quick peek at this already.  There have been some changes in the base Cacti code which means that functions which should have their error trapping suppressed by @ will not correctly do this.  The unpack statement has such a statement so it should have suppressed the error rather than reporting it.

As long as you have updated your version of Cacti, you should no longer see these errors.
