### ISSUE TITLE
Flowview not showing flows in Cacti GUI

### ISSUE THREAD

**Issue by ericfretz** [Cacti/plugin_flowview#65]
Flowview v3.2 installed on Cacti 1.2.16 (Ubuntu 20.04.2 LTS)

The problem:  Flows are not appearing when flow queries are run.

Things I have verified:
- flow-capture is running (via systemctl service) for each of my listeners
- Netflow v9 reports are being received from my Meraki devices to the listeners and this was verified by select * from plugin_flowview_raw table.
- Cacti reports the listeners as being "UP"

How do I verify the received netflow reports are properly formatted?

**Comment by mbracale** [comment]
Noticed that since 3.x version, "flow directory" configuration disappeared from "Cacti > Settings > Misc" page. On v2.2 with the correct path set, flowview show the flows table. Even after upgrading and leaving mysql cacti settings table "path_flows_dir" with the correct path, flowview still don't work. 
Couldn't find the path configuration anywhere else, so I imagine its looking at a different directory than the one I'm saving my flows.

**Comment by TheWitness** [comment]
Yes, that's cause we no longer use those flow* commands to capture and report generation.  We have our own php collector and use SQL queries to generate the reports.  It becomes much more scalable and supportable.  So, there is no need for that directory, left it in the dust.

**Comment by mbracale** [comment]
Thanks @TheWitness .. really missed that "little" detail in the documentation.

@ericfretz Have you tried to create a filter including the listener you created, and then using this filter on the FlowView tab?

**Comment by TheWitness** [comment]
@ericfretz and @mbracale.  Okay, just going to close this.  I'm spending some time on this plugin to correct some smalish bugs, no big changes.  So, you might want to update to develop.
