### ISSUE TITLE
flowview nodata plugin_flowview_raw_2022177 no data

### ISSUE THREAD

**Issue by teesa-git** [Cacti/plugin_flowview#78]
**Describe the bug**
flowview nodata plugin_flowview_raw_2022177 no data

**Screenshots**
![image](https://user-images.githubusercontent.com/52067473/176067376-6c22eb1a-0861-4c1a-88dc-17d3e51f9654.png)
![image](https://user-images.githubusercontent.com/52067473/176067449-2741114a-168a-47b7-91bc-4a91d444f903.png)
![image](https://user-images.githubusercontent.com/52067473/176067496-f031ce49-af55-47a3-bfd5-19d2aebaa85f.png)
![image](https://user-images.githubusercontent.com/52067473/176067512-bed2ac4f-8322-43ba-8081-f2a1d6ee85c2.png)
![image](https://user-images.githubusercontent.com/52067473/176067579-bae720b1-417d-490c-bf16-ece478ed0612.png)
![image](https://user-images.githubusercontent.com/52067473/176067607-dd98f243-4fe6-457a-8c38-9a1cc62e0baf.png)

**Comment by Double-Domination** [comment]
Same problem, flow-view version 3.3. Ubuntu 22.04 Cactid flow-capture and  daemons up and running, listener is configured too.
![image](https://user-images.githubusercontent.com/61385200/177302676-c10886a0-f953-47ed-b701-b680b476e413.png)

systemctl:
![image](https://user-images.githubusercontent.com/61385200/177303061-c08ace83-fc68-4c05-bf28-cd598ae6971d.png)

NetFlow data passed via port 9996
![image](https://user-images.githubusercontent.com/61385200/177304548-56d6474f-91b6-42ed-8e7c-8b107705db2d.png)

Interesting fact: In settings dialog(misc)  parameter "netflow directory" is missing. I focus my sight on this fact, because in prev versions of flow view plugin this setting has been in Settings.  Absolutely no idea what went wrong (no errors from cacti)
![image](https://user-images.githubusercontent.com/61385200/177304968-c692fe80-7864-4e5f-b8c6-5b8635ab662c.png)
![image](https://user-images.githubusercontent.com/61385200/177305170-4b323464-e383-4722-8ed1-c47fef9d1109.png)

**Comment by TheWitness** [comment]
There is no flowview directory in this release.  Note your issue may be different.  Have you created/selected a filter?

**Comment by Double-Domination** [comment]
> There is no flowview directory in this release. Note your issue may be different. Have you created/selected a filter?

Filter doesn't change anything:
![image](https://user-images.githubusercontent.com/61385200/177459350-0b8f961b-9725-4911-9c79-12b9b4d3bc8b.png)
![image](https://user-images.githubusercontent.com/61385200/177459402-6cb20be0-ce3e-453a-8c22-d0d67ccdba72.png)

But, after filter creation some errors appeared:
![image](https://user-images.githubusercontent.com/61385200/177459760-c8a19017-131e-4a55-b404-f10fb4d1ca94.png)

**Comment by TheWitness** [comment]
I'm going to close this ticket and describe some etiquette. First, you poached another users ticket for a separate issue and that the most important thing.

Second, it looks like this was an upgrade, and they are really not supported for this community plugin.  Likely the best thing to do would be to uninstall the plugin first, make sure all the flowview tables are dropped, and then reinstall.  At that point, if you are receiving errors, open your own ticket.

@teesa-git, apologies.  If your issue still persistst, open a new ticket.
